import type { PdfReaderSource } from '@/components/content/pdf-reader';
import { formatFileSize } from '@/lib/utils';

/**
 * PDF gallery data.
 *
 * A gallery lives in a `PDF_GALLERY` section's `content.items`, which is the
 * same open JSON record every other section type stores its copy in — no new
 * table, no parallel storage, and a page that predates the feature is
 * unaffected because a section without the key simply reads as an empty
 * gallery.
 *
 * Both halves of the feature read the list through `readPdfGalleryItems`: the
 * public renderer and the admin editor. That is deliberate. Section content is
 * hand-editable through the API and survives across deploys, so a malformed or
 * half-written item has to degrade to "not shown" rather than throw — the same
 * contract the section accessors in `components/sections/types.ts` keep.
 */

/**
 * One document in a gallery.
 *
 * `mediaId` is the only thing that identifies the file. The URL the reader
 * streams from is derived from it (`documentStreamPath`) rather than stored,
 * so moving from local disk to S3 — or changing the route — needs no data
 * migration and cannot leave a section pointing at a URL that no longer
 * resolves. The cover is the exception: it is an ordinary image rendered
 * through `<img>`, so it is stored as a URL exactly like every other section
 * image.
 */
export interface PdfGalleryItem {
  /** Stable across edits and reorders, so React keys and the viewer's
   *  remembered page do not follow the list position. */
  id: string;
  mediaId: string;
  /** Original upload name — the reader's chrome and the download use it. */
  fileName: string;
  sizeBytes: number;
  title: string;
  description?: string;
  /** Cover image chosen or generated by an editor. */
  coverUrl?: string;
  coverMediaId?: string;
  /** Known when the cover was generated in the browser; shown as metadata. */
  pageCount?: number;
}

/**
 * A ceiling on one section, not on the feature.
 *
 * Sections are stored as a single JSON column and rendered in one pass, so a
 * gallery of a thousand documents is a slow page and an unreadable editor
 * rather than a useful one. Several gallery sections on a page are the answer
 * to a genuinely large library.
 */
export const MAX_PDF_GALLERY_ITEMS = 60;

/** Where the in-browser reader streams a published document from. */
export function documentStreamPath(mediaId: string): string {
  return `/api/v1/documents/${encodeURIComponent(mediaId)}`;
}

/** The source the reader opens, for one gallery item. */
export function toPdfReaderSource(item: PdfGalleryItem): PdfReaderSource {
  return {
    url: documentStreamPath(item.mediaId),
    fileName: item.fileName,
    sizeBytes: item.sizeBytes,
  };
}

function readText(source: Record<string, unknown>, key: string): string | undefined {
  const value = source[key];
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function readCount(source: Record<string, unknown>, key: string): number | undefined {
  const value = source[key];
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) return undefined;
  return Math.floor(value);
}

/**
 * An image URL a section may render.
 *
 * Same rule the section actions use: site-relative or `http(s)` only, so a
 * stored value can never become a `javascript:` or `data:` source.
 */
function readImageUrl(source: Record<string, unknown>, key: string): string | undefined {
  const value = readText(source, key);
  if (!value) return undefined;
  return value.startsWith('/') || /^https?:\/\//i.test(value) ? value : undefined;
}

/** Reads a gallery out of a section's content, skipping anything unusable. */
export function readPdfGalleryItems(content: Record<string, unknown>): PdfGalleryItem[] {
  const raw = content.items;
  if (!Array.isArray(raw)) return [];

  const items: PdfGalleryItem[] = [];

  for (const entry of raw.slice(0, MAX_PDF_GALLERY_ITEMS)) {
    if (!entry || typeof entry !== 'object') continue;
    const record = entry as Record<string, unknown>;

    // Without a media id there is nothing to stream, so the card would be a
    // link to nowhere. Drop it rather than render a broken tile.
    const mediaId = readText(record, 'mediaId');
    if (!mediaId) continue;

    const fileName = readText(record, 'fileName') ?? 'document.pdf';
    const description = readText(record, 'description');
    const coverUrl = readImageUrl(record, 'coverUrl');
    const coverMediaId = readText(record, 'coverMediaId');
    const pageCount = readCount(record, 'pageCount');

    items.push({
      id: readText(record, 'id') ?? mediaId,
      mediaId,
      fileName,
      sizeBytes: readCount(record, 'sizeBytes') ?? 0,
      // A gallery built before titles were filled in still reads: the file
      // name is what the editor saw when they added it.
      title: readText(record, 'title') ?? fileName,
      ...(description ? { description } : {}),
      ...(coverUrl ? { coverUrl } : {}),
      ...(coverMediaId ? { coverMediaId } : {}),
      ...(pageCount ? { pageCount } : {}),
    });
  }

  return items;
}

/**
 * The metadata line under a card title: `12 pages · 2.4 MB`.
 *
 * Both halves are optional. A page count exists only where a cover was
 * generated in the browser, and a size of zero means a hand-written item, so
 * whichever is known is shown and an item that knows neither simply has no
 * metadata line rather than a row of dashes.
 */
export function describePdfItem(item: PdfGalleryItem): string {
  const parts: string[] = [];
  if (item.pageCount) parts.push(`${item.pageCount} ${item.pageCount === 1 ? 'page' : 'pages'}`);
  const size = formatFileSize(item.sizeBytes);
  if (size) parts.push(size);
  return parts.join(' · ');
}
